from cookiecutter import utils as utils
from cookiecutter.environment import StrictEnvironment as StrictEnvironment
from cookiecutter.exceptions import FailedHookException as FailedHookException
from typing import Any

logger: Any
EXIT_SUCCESS: int

def valid_hook(hook_file: Any, hook_name: Any): ...
def find_hook(hook_name: Any, hooks_dir: str = ...): ...
def run_script(script_path: Any, cwd: str = ...) -> None: ...
def run_script_with_context(script_path: Any, cwd: Any, context: Any) -> None: ...
def run_hook(hook_name: Any, project_dir: Any, context: Any) -> None: ...
