from cookiecutter.environment import StrictEnvironment as StrictEnvironment
from cookiecutter.exceptions import UndefinedVariableInTemplate as UndefinedVariableInTemplate
from typing import Any

def read_user_variable(var_name: Any, default_value: Any): ...
def read_user_yes_no(question: Any, default_value: Any): ...
def read_repo_password(question: Any): ...
def read_user_choice(var_name: Any, options: Any): ...
def process_json(user_value: Any): ...
def read_user_dict(var_name: Any, default_value: Any): ...
def render_variable(env: Any, raw: Any, cookiecutter_dict: Any): ...
def prompt_choice_for_config(cookiecutter_dict: Any, env: Any, key: Any, options: Any, no_input: Any): ...
def prompt_for_config(context: Any, no_input: bool = ...): ...
