from cookiecutter.exceptions import RepositoryNotFound as RepositoryNotFound
from cookiecutter.vcs import clone as clone
from cookiecutter.zipfile import unzip as unzip
from typing import Any, Optional

REPO_REGEX: Any

def is_repo_url(value: Any): ...
def is_zip_file(value: Any): ...
def expand_abbreviations(template: Any, abbreviations: Any): ...
def repository_has_cookiecutter_json(repo_directory: Any): ...
def determine_repo_dir(template: Any, abbreviations: Any, clone_to_dir: Any, checkout: Any, no_input: Any, password: Optional[Any] = ..., directory: Optional[Any] = ...): ...
