from cookiecutter.prompt import read_user_yes_no as read_user_yes_no
from typing import Any, Optional

logger: Any

def force_delete(func: Any, path: Any, exc_info: Any) -> None: ...
def rmtree(path: Any) -> None: ...
def make_sure_path_exists(path: Any): ...
def work_in(dirname: Optional[Any] = ...) -> None: ...
def make_executable(script_path: Any) -> None: ...
def prompt_and_delete(path: Any, no_input: bool = ...): ...
