---
name: CICD
on: [push]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install python
        run: |
          sudo apt-get update
          sudo apt-get install python3.8-dev python3.9-dev
          sudo apt-get install python3-distutils
      - name: Install tox
        run: |
          pip install setuptools wheel
          pip install tox
      - name: Run tests
        run: |
          python -m tox -e py38-test,py39-test
      - name: Run linters
        run: |
          python -m tox -e lint
      - name: Check coverage
        run: |
          python -m tox -e coverage
      - name: Check build
        run: |
          python -m tox -e build
#       - name: Slack notification
#         uses: homoluctus/slatify@master
#         if: always()
#         with:
#           type: ${{ job.status }}
#           job_name: '*Tests*'
#           mention: 'here'
#           mention_if: 'failure'
#           channel: '#devops'
#           url: ${{ secrets.SLACK_WEBHOOK }}
#           commit: true
#           token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: Release and deploy.
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Install python
        run: |
          sudo apt-get update
          sudo apt-get install python3.9 python3-distutils python3.9-dev
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel tox
      - name: Build package
        run: |
          python -m tox -e build
      - name: Tag release
        run: |
          python -m tox -e invoke tagrelease
#       - name: Publish package
#         uses: pypa/gh-action-pypi-publish@master
#         with:
#           user: __token__
#           password: ${{ secrets.pypi_password }}
#           repository_url: https://test.pypi.org/legacy/
      - name: Bump version
        run: |
          env
          git config user.name "CICD"
          git config user.email "deployment@einara.com"
          git pull
          git checkout develop
          python -m tox -e invoke -- bumpversion --commit
          git push
#       - name: Slack Notification
#         uses: homoluctus/slatify@master
#         if: always()
#         with:
#           type: ${{ job.status }}
#           job_name: '*Deploy to PyPI*'
#           mention: 'here'
#           mention_if: 'failure'
#           channel: '#devops'
#           url: ${{ secrets.SLACK_WEBHOOK }}
#           commit: true
#           token: ${{ secrets.GITHUB_TOKEN }}

